# Radio-Mapper Emergency Response System Configuration
# Example: North Oklahoma City Buoy

# Buoy Configuration  
buoy:
  id: "OKC_BUOY_NORTH"
  name: "Oklahoma City North Buoy"
  
  # Physical Location - North OKC (near Edmond)
  location:
    latitude: 35.5276     # North of downtown
    longitude: -97.5164
    altitude: 380.0
    
  # GPS Configuration
  gps:
    enabled: true
    device: "/dev/ttyUSB0"
    backup_device: "/dev/ttyACM0"
    timeout_seconds: 30
    use_fallback_location: true
    
# Central Server Configuration (same for all buoys)
central_server:
  # Connect to central server (replace with actual server IP)
  websocket_url: "ws://your-server.com:8081"
  http_url: "http://your-server.com:5001"
  
  # For running central server (only on main machine)
  bind_host: "0.0.0.0"
  websocket_port: 8081
  http_port: 5001 